compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@vitejs/plugin-vue-jsx@*":
    dependencies:
      vite: "*"
  "@vitejs/plugin-vue@*":
    dependencies:
      vite: "*"
  markdown-it-mdc@*:
    dependencies:
      "@types/markdown-it": "*"
  postcss-nested@*:
    dependencies:
      postcss: "*"
  twoslash-vue@*:
    dependencies:
      typescript: "*"
  twoslash@*:
    dependencies:
      typescript: "*"
  unplugin-vue-markdown@*:
    dependencies:
      vite: "*"
  vite-plugin-remote-assets@*:
    dependencies:
      vite: "*"
  vite-plugin-vue-server-ref@*:
    dependencies:
      vite: "*"
  vue-demi@*:
    dependencies:
      vue: "*"

yarnPath: .yarn/releases/yarn-4.7.0.cjs
