nodeLinker: node-modules
packageExtensions:
  'vue-demi@*':
    dependencies:
      'vue': '*'
  'twoslash@*':
    dependencies:
      typescript: '*'
  'twoslash-vue@*':
    dependencies:
      typescript: '*'
  'markdown-it-mdc@*':
    dependencies:
      '@types/markdown-it': '*'
  'postcss-nested@*':
    dependencies:
      'postcss': '*'
  '@vitejs/plugin-vue-jsx@*':
    dependencies:
      'vite': '*'
  '@vitejs/plugin-vue@*':
    dependencies:
      'vite': '*'
  'unplugin-vue-markdown@*':
    dependencies:
      'vite': '*'
  'vite-plugin-remote-assets@*':
    dependencies:
      'vite': '*'
  'vite-plugin-vue-server-ref@*':
    dependencies:
      'vite': '*'
